name: Build
'on':
  push:
    branches:
      - test-branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm test
      - name: Publish
        uses: dylanvann/publish-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
#npm run should generate the dist folder etc, look into this after